description = "adding features"
prompt = """
Execute these tasks in order:

1.add calendar package that can make appointments saved in calendar events
2.add a checkbox in the appointment confirmation dialogue that is checked by default that asks user to add the appointment to calendar if they confirm and the box is checked trigger a proper function that adds it
3.add a scanner package that has to side one for clinc which generate a special QR code for them which can be accessed in clinic settings
4.users will have a scanner icon in favorite page which can scan a clinic QR code and add them to favorite list
5.run a review of the project and create file which will contains firebase rules that suits the project specially that i have permission issues when trying to add clincs to favorite


"""